name: Pipeline CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v1.2.1
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectKey: c_snake
          projectName: C Snake Game
          projectVersion: ${{ github.sha }}
          sources: .
          extraProperties: |
            sonar.sources=src
            sonar.c.file.suffixes=.c,.h
            sonar.exclusions=**/tests/**,**/build/**

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ make libsfml-dev lcov

      - name: Compile project
        run: |
          g++ -std=c++17 -Wall -Wextra -pedantic main.cpp -o snake_game -lsfml-graphics -lsfml-window -lsfml-system

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: snake-game-linux
          path: snake_game
